name: minerl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - py-opencv
  - cudatoolkit=10.2
  - pip:
    - git+https://github.com/minerllabs/minerl
    - coloredlogs
    - matplotlib
    # - -e ./external_libs/vpt/
    # - -e ./external_libs/fractal-zero/
    - gym==0.19  # required gym version for my cases.
    - aicrowd-api
    - aicrowd-gym

